"""MSG91 provider implementations for email (and later WhatsApp).

MSG91 email API: https://docs.msg91.com/reference/send-email
Auth: `authkey` request header.

Two templates in use:
  - Appointment:  template_13_09_2026_19_09
      variables: user_name, appointment_date_and_time, centre_name
  - Bill:         invoice_user_name_paineasy_2
      variables: User_name

Every failure is *returned* as MessageResult(success=False), never raised.
The appointment is already committed / the PDF is already generated by the time
this is called — a messaging fault must not become a 500.
"""

import base64
import logging

import httpx

from app.integrations.base import EmailService, MessageResult
from app.models.enums import MessageChannel

logger = logging.getLogger(__name__)

_MSG91_EMAIL_URL = "https://control.msg91.com/api/v5/email/send"


class MSG91EmailService(EmailService):
    """Transactional email via MSG91's template API."""

    name = "msg91_email"

    def __init__(
        self,
        *,
        auth_key: str,
        domain: str,
        from_email: str,
        appt_template_id: str,
        bill_template_id: str,
        timeout: int = 20,
    ) -> None:
        self._auth_key = auth_key
        self._domain = domain
        self._from_email = from_email
        self._appt_template_id = appt_template_id
        self._bill_template_id = bill_template_id
        self._timeout = timeout

    # ---------------------------------------------------------------------- #
    # Public interface (satisfies EmailService ABC)
    # ---------------------------------------------------------------------- #
    def send(
        self,
        *,
        to: str,
        subject: str,
        body: str,
        html_body: str | None = None,
        attachments: list[tuple[str, bytes]] | None = None,
        # MSG91-specific extras (passed through by our internal callers)
        recipient_name: str | None = None,
        template_id: str | None = None,
        variables: dict | None = None,
    ) -> MessageResult:
        """Send one email.

        `template_id` overrides the default appointment template.
        `variables` is the exact dict sent to MSG91 — key names must match
        the placeholders in the MSG91 template editor exactly.
        `attachments` is [(filename, bytes)] — PDFs are base64-encoded as a
        data-URI, which is the format MSG91 requires.
        """
        tid = template_id or self._appt_template_id
        vars_map: dict = {**(variables or {})}
        return self._post(to=to, recipient_name=recipient_name,
                          template_id=tid, variables=vars_map,
                          attachments=attachments)

    def send_appointment(
        self,
        *,
        to: str,
        patient_name: str,
        appointment_datetime: str,
        centre_name: str,
    ) -> MessageResult:
        """Send appointment confirmation using the appointment template.

        Variable names match the MSG91 template exactly:
          user_name, appointment_date_and_time, centre_name
        """
        return self._post(
            to=to,
            recipient_name=patient_name,
            template_id=self._appt_template_id,
            variables={
                "user_name": patient_name,
                "appointment_date_and_time": appointment_datetime,
                "centre_name": centre_name,
            },
        )

    def send_bill(
        self,
        *,
        to: str,
        patient_name: str,
        attachments: list[tuple[str, bytes]] | None = None,
    ) -> MessageResult:
        """Send bill using the invoice template, with PDF attached."""
        return self._post(
            to=to,
            recipient_name=patient_name,
            template_id=self._bill_template_id or self._appt_template_id,
            variables={"User_name": patient_name},
            attachments=attachments,
        )

    # ---------------------------------------------------------------------- #
    # Internal
    # ---------------------------------------------------------------------- #
    def _post(
        self,
        *,
        to: str,
        recipient_name: str | None,
        template_id: str,
        variables: dict,
        attachments: list[tuple[str, bytes]] | None = None,
    ) -> MessageResult:
        if not self._auth_key:
            return self._fail(to, "CLINIC_MSG91_AUTH_KEY not set in .env")
        if not self._domain:
            return self._fail(to, "CLINIC_MSG91_EMAIL_DOMAIN not set in .env")
        if not self._from_email:
            return self._fail(to, "CLINIC_MSG91_EMAIL_FROM not set in .env")
        if not template_id:
            return self._fail(to, "No MSG91 email template id configured")

        payload: dict = {
            "recipients": [
                {
                    "to": [{"email": to, "name": recipient_name or ""}],
                    "variables": variables,
                }
            ],
            "from": {"email": self._from_email},
            "domain": self._domain,
            "template_id": template_id,
        }

        if attachments:
            # MSG91 requires data-URI: "data:<mime>;base64,<data>"
            payload["attachments"] = [
                {
                    "filename": name,
                    "file": f"data:application/pdf;base64,{base64.b64encode(data).decode()}",
                }
                for name, data in attachments
            ]

        try:
            resp = httpx.post(
                _MSG91_EMAIL_URL,
                json=payload,
                headers={"authkey": self._auth_key, "Content-Type": "application/json"},
                timeout=self._timeout,
            )
        except httpx.HTTPError as exc:
            return self._fail(to, f"Network error: {exc}")

        try:
            data = resp.json()
        except Exception:
            data = {}

        if resp.status_code not in (200, 201) or data.get("hasError"):
            errors = data.get("errors") or {}
            msg = data.get("message") or resp.text[:300]
            if errors:
                msg = f"{msg} — {errors}"
            return self._fail(to, f"MSG91 {resp.status_code}: {msg}")

        unique_id = (data.get("data") or {}).get("unique_id") or ""
        logger.info("MSG91 email queued to %s (template=%s id=%s)", to, template_id, unique_id)
        return MessageResult(
            success=True,
            provider=self.name,
            channel=MessageChannel.EMAIL,
            recipient=to,
            provider_message_id=unique_id or None,
        )

    @staticmethod
    def _fail(to: str, error: str) -> MessageResult:
        logger.warning("MSG91EmailService: %s — %s", to, error)
        return MessageResult(
            success=False,
            provider="msg91_email",
            channel=MessageChannel.EMAIL,
            recipient=to,
            error=error,
        )
