"""per-clinic branding and invoice series

Revision ID: 13da18c67195
Revises: 95ed5301d7fc
Create Date: 2026-08-24 14:08:17.939130
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '13da18c67195'
down_revision: str | None = '95ed5301d7fc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('brand_tagline', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('logo_filename', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('document_footer', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('bill_number_prefix', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.drop_column('bill_number_prefix')
        batch_op.drop_column('document_footer')
        batch_op.drop_column('logo_filename')
        batch_op.drop_column('brand_tagline')
        batch_op.drop_column('brand_name')

    # ### end Alembic commands ###
