"""add patient whatsapp_number

Revision ID: 6110469b2e24
Revises: 55e390c3e391
Create Date: 2026-08-21 15:48:02.823455
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '6110469b2e24'
down_revision: str | None = '55e390c3e391'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('whatsapp_number', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_patients_whatsapp_number'), ['whatsapp_number'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_whatsapp_number'))
        batch_op.drop_column('whatsapp_number')

    # ### end Alembic commands ###
