"""session void trail

Revision ID: 93bcd242021e
Revises: 6110469b2e24
Create Date: 2026-08-22 13:13:28.825008
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '93bcd242021e'
down_revision: str | None = '6110469b2e24'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_sessions', schema=None) as batch_op:
        # server_default is required: the column is NOT NULL and this table
        # already has rows, which would otherwise have nothing to put in it.
        batch_op.add_column(
            sa.Column(
                'is_voided', sa.Boolean(), nullable=False, server_default=sa.false()
            )
        )
        batch_op.add_column(sa.Column('void_reason', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('voided_by_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_patient_sessions_is_voided'), ['is_voided'], unique=False)
        batch_op.create_foreign_key('fk_patient_sessions_voided_by_user_id', 'users', ['voided_by_user_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_sessions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_patient_sessions_voided_by_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_patient_sessions_is_voided'))
        batch_op.drop_column('voided_at')
        batch_op.drop_column('voided_by_user_id')
        batch_op.drop_column('void_reason')
        batch_op.drop_column('is_voided')

    # ### end Alembic commands ###
