"""service catalogue and bill item link

Revision ID: 95ed5301d7fc
Revises: 93bcd242021e
Create Date: 2026-08-22 15:26:57.594872
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '95ed5301d7fc'
down_revision: str | None = '93bcd242021e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('item_type', sa.Enum('SESSION_PACKAGE', 'CONSULTATION', 'PRODUCT', 'OTHER', name='billitemtype', native_enum=False, length=40), nullable=False),
    sa.Column('default_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('default_price >= 0', name='ck_service_items_price_non_negative'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinic_id', 'name', name='uq_service_items_clinic_name')
    )
    with op.batch_alter_table('service_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_items_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_items_name'), ['name'], unique=False)

    with op.batch_alter_table('bill_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_item_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_bill_items_service_item_id', 'service_items', ['service_item_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill_items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_bill_items_service_item_id', type_='foreignkey')
        batch_op.drop_column('service_item_id')

    with op.batch_alter_table('service_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_items_name'))
        batch_op.drop_index(batch_op.f('ix_service_items_clinic_id'))

    op.drop_table('service_items')
    # ### end Alembic commands ###
