"""user employee id and registration number

Revision ID: e20e54ab7386
Revises: 13da18c67195
Create Date: 2026-08-25 09:09:39.825032
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e20e54ab7386'
down_revision: str | None = '13da18c67195'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('registration_number', sa.String(length=60), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_employee_id'), ['employee_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_employee_id'))
        batch_op.drop_column('registration_number')
        batch_op.drop_column('employee_id')

    # ### end Alembic commands ###
